## Numpy

In [13]:
import numpy as np
import pandas as pd
import time

In [2]:
ruta = '/home/anderson-josue/Documents/Data Science/Day 8 /Ciudades_Visitadas_Latinoamerica_2023.csv'
df = pd.read_csv(ruta)
df

Ciudad       País  Población  Visitantes
0   Ciudad de México     México    9265833    21000000
1       Buenos Aires  Argentina    3059574    15000000
2     Río de Janeiro     Brasil    6748314    13000000
3               Lima       Perú    9756020     9000000
4             Bogotá   Colombia    7181663     8000000
5  Santiago de Chile      Chile    6199241     7500000
6          São Paulo     Brasil   12333146    20000000
7          La Habana       Cuba    2164182     4000000
8             Cancún     México     888124     5000000
9          Cartagena   Colombia    1036671     3000000

In [3]:
df['Población'].mean()

5863276.8

In [5]:
np.round(df['Población'].mean())

5863277.0

In [6]:
np.min(df['Población'])

888124

In [7]:
np.max(df['Población'])

12333146

In [9]:
mi_array = np.array([1, 2, 3, 4, 5])
mi_array

array([1, 2, 3, 4, 5])

In [10]:
type(mi_array)

numpy.ndarray

In [11]:
lista_grande = list(range(1000000))
array_grande = np.array(lista_grande)

In [12]:
type(lista_grande)
type(array_grande)

numpy.ndarray

In [15]:
inicio = time.time()
for i in lista_grande:
    i ** 2
fin = time.time()
print(fin - inicio)

0.07504630088806152


In [17]:
inicio = time.time()
array_grande ** 2
fin = time.time()
print(fin - inicio)

0.007486581802368164


In [19]:
array = np.array([1, 2, 3])

In [20]:
len(array)

3

In [21]:
array.shape

(3,)

In [22]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array_2d.shape

(2, 3)

In [25]:
x = [1, 2, 3]
y = [1, 2, 3]
z = [1, 2, 3]

In [27]:
np.concatenate([x, y, z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [28]:
a = [[1, 2], [3, 4]]
b = [[5, 6], [7, 8]]


In [29]:
np.concatenate([a, b], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
array_concatenado = np.concatenate([a, b], axis=0)
array_concatenado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
array_concatenado.shape

(4, 2)

In [36]:
array_reformado = array_concatenado.reshape(2,4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
array_sumado = array_reformado + array_reformado
array_sumado

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [39]:
array_multi = array_reformado * array_reformado
array_multi

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [41]:
raices = np.sqrt(array_multi)
raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [42]:
array_original = np.array([1,2,3,4,5,6])
array_original

array([1, 2, 3, 4, 5, 6])

In [43]:
array_reshaped = array_original.reshape(2,3)
array_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
array1d = np.array([1, 2, 3, 4, 5])

In [45]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
array1d[0]

1

In [48]:
array1d[1]


2

In [49]:
array1d[-1]

5

In [50]:
array2d[0]

array([1, 2, 3])

In [51]:
array2d[1]

array([4, 5, 6])

In [52]:
array2d[2]

array([7, 8, 9])

In [53]:
array2d[1][2]

6

In [54]:
array1d[1:4]

array([2, 3, 4])

In [55]:
array2d[1, :]

array([4, 5, 6])

In [56]:
array2d[1, 1:3]

array([5, 6])

In [58]:
array2d[:, 0]

array([1, 4, 7])

In [59]:
array2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [60]:
array1d > 3

array([False, False, False,  True,  True])

In [61]:
array2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [63]:
numeros = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
segunda_fila = numeros[2:]
segunda_fila

array([[7, 8, 9]])

In [64]:
array = np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
array.shape

(9,)

In [66]:
array_modificado = array.reshape(3, 3)
array_modificado

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
array_mod2 = array.reshape(-1, 3)
array_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
array_t = array_mod2.transpose()
array_t

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
array_chato = array_t.flatten()
array_chato

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [73]:
array_ravel = array_t.ravel()
array_ravel

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [74]:
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [75]:
array2 = np.array([[0],[10],[20],[30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [77]:
broadcaast_suma = array2 + array1
broadcaast_suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [78]:
broadcaast_multi = array2 * array1
broadcaast_multi

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [79]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [80]:
resultado = np.add(a, b)
resultado

array([5, 7, 9])

In [81]:
# substract, multiply, divide

In [82]:
resultado2 = np.exp(a)
resultado2

array([ 2.71828183,  7.3890561 , 20.08553692])

In [83]:
resultado3 = np.log(a)
resultado3

array([0.        , 0.69314718, 1.09861229])

In [84]:
resultado4 = np.sqrt(a)
resultado4

array([1.        , 1.41421356, 1.73205081])

In [85]:
array = np.array([1, 2, np.nan, 4, 5])
array

array([ 1.,  2., nan,  4.,  5.])

In [86]:
np.isnan(array)

array([False, False,  True, False, False])

In [87]:
np.mean(array)

nan

In [88]:
np.nanmean(array)

3.0

In [89]:
array_con_0 = np.where(np.isnan(array), 0, array)
array_con_0

array([1., 2., 0., 4., 5.])

In [90]:
promedio = np.nanmean(array)
array_promedio = np.where(np.isnan(array), promedio, array)
array_promedio


array([1., 2., 3., 4., 5.])

In [91]:
array_filtrado = array[np.isnan(array)]
array_filtrado

array([nan])

In [92]:
array_filtrado = array[~np.isnan(array)]
array_filtrado

array([1., 2., 4., 5.])

In [93]:
ruta = '/home/anderson-josue/Documents/Data Science/Day 8 /medallas.csv'


In [94]:
array = np.genfromtxt(ruta)

ValueError: Some errors were detected !
    Line #15 (got 2 columns instead of 1)
    Line #17 (got 2 columns instead of 1)
    Line #20 (got 2 columns instead of 1)
    Line #22 (got 2 columns instead of 1)
    Line #24 (got 2 columns instead of 1)
    Line #27 (got 4 columns instead of 1)
    Line #36 (got 2 columns instead of 1)
    Line #39 (got 3 columns instead of 1)
    Line #44 (got 4 columns instead of 1)
    Line #63 (got 2 columns instead of 1)
    Line #65 (got 2 columns instead of 1)
    Line #70 (got 2 columns instead of 1)
    Line #72 (got 3 columns instead of 1)
    Line #73 (got 3 columns instead of 1)
    Line #74 (got 4 columns instead of 1)
    Line #77 (got 2 columns instead of 1)
    Line #78 (got 2 columns instead of 1)
    Line #82 (got 2 columns instead of 1)
    Line #86 (got 3 columns instead of 1)

In [96]:
array = np.genfromtxt(ruta, delimiter=',')
array

array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,   1.,   2.,   3.,  nan],
       [ nan,   2.,   2.,   4.,  nan],
       [ 17.,   7.,  22.,  46.,  nan],
       [  1.,   1.,   5.,   7.,  nan],
       [ nan,   3.,   4.,   7.,  nan],
       [  2.,  nan,  nan,   2.,  nan],
       [ nan,   1.,  nan,   1.,  nan],
       [  1.,   3.,   3.,   7.,  nan],
       [  3.,   1.,   3.,   7.,  nan],
       [  1.,  nan,  nan,   1.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,   8.,  21.,  nan],
       [  3.,   1.,   2.,   6.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   6.,  11.,  24.,  nan],
       [  2.,   4.,   6.,  12.,  nan],
       [ nan,   4.,   1.,   5.,  nan],
       [  3.,   3.,   2.,   8.,  nan],
       [ nan,  nan,   1.,   1.,  nan],
       [  7.,   3.,   5.,  15.,  nan],
       [  4.,   4.,   3.,  11.,  nan],
       [  3.,   4.,   4.,  11.,  nan],
       [ nan,   3.,   2.,   5.,  nan],
       [  2.,   1.,  nan,   3.,  nan],
       [  1.,   1.,   4.,

In [97]:
array = np.genfromtxt(ruta, delimiter=',', filling_values=0)
array

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,

In [98]:
array = np.genfromtxt(ruta, delimiter=',', filling_values=0, skip_header=1)
array

array([[  0.,   1.,   2.,   3.,   0.],
       [  0.,   2.,   2.,   4.,   0.],
       [ 17.,   7.,  22.,  46.,   0.],
       [  1.,   1.,   5.,   7.,   0.],
       [  0.,   3.,   4.,   7.,   0.],
       [  2.,   0.,   0.,   2.,   0.],
       [  0.,   1.,   0.,   1.,   0.],
       [  1.,   3.,   3.,   7.,   0.],
       [  3.,   1.,   3.,   7.,   0.],
       [  1.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,   8.,  21.,   0.],
       [  3.,   1.,   2.,   6.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   6.,  11.,  24.,   0.],
       [  2.,   4.,   6.,  12.,   0.],
       [  0.,   4.,   1.,   5.,   0.],
       [  3.,   3.,   2.,   8.,   0.],
       [  0.,   0.,   1.,   1.,   0.],
       [  7.,   3.,   5.,  15.,   0.],
       [  4.,   4.,   3.,  11.,   0.],
       [  3.,   4.,   4.,  11.,   0.],
       [  0.,   3.,   2.,   5.,   0.],
       [  2.,   1.,   0.,   3.,   0.],
       [  1.,   1.,   4.,   6.,   0.],
       [ 39.,  41.,  33.,

In [99]:
array = np.genfromtxt(ruta, delimiter=',', filling_values=0, skip_header=1, dtype=int)
array

array([[  0,   1,   2,   3,   0],
       [  0,   2,   2,   4,   0],
       [ 17,   7,  22,  46,   0],
       [  1,   1,   5,   7,   0],
       [  0,   3,   4,   7,   0],
       [  2,   0,   0,   2,   0],
       [  0,   1,   0,   1,   0],
       [  1,   3,   3,   7,   0],
       [  3,   1,   3,   7,   0],
       [  1,   0,   0,   1,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,   8,  21,   0],
       [  3,   1,   2,   6,   0],
       [  0,   0,   1,   1,   0],
       [  7,   6,  11,  24,   0],
       [  2,   4,   6,  12,   0],
       [  0,   4,   1,   5,   0],
       [  3,   3,   2,   8,   0],
       [  0,   0,   1,   1,   0],
       [  7,   3,   5,  15,   0],
       [  4,   4,   3,  11,   0],
       [  3,   4,   4,  11,   0],
       [  0,   3,   2,   5,   0],
       [  2,   1,   0,   3,   0],
       [  1,   1,   4,   6,   0],
       [ 39,  41,  33, 113,   0],
       [  1,   0,   1,   2,   0],
       [  1,   1,   2,   4,   0],
       [  1,   0,   1,   2,   0],
       [  0,  

In [100]:
array_ejemplo = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

In [101]:
ruta ='/home/anderson-josue/Documents/Data Science/Day 8 /array.csv'

In [103]:
np.savetxt(ruta, array_ejemplo, delimiter=',', fmt='%d')

In [105]:
df = pd.DataFrame(
    {
        "Impares": [1, 3, 5],
        "Pares": [2, 4, 6],
    }
)
df

Impares  Pares
0        1      2
1        3      4
2        5      6

In [107]:
array_np1 = df.values
array_np1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
array_np2 =df.to_numpy()
array_np2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
np.sqrt(df)

Impares     Pares
0  1.000000  1.414214
1  1.732051  2.000000
2  2.236068  2.449490

In [110]:
np.max(df)

6

In [111]:
df_desde_numpy = pd.DataFrame(array_np1)
df_desde_numpy

0  1
0  1  2
1  3  4
2  5  6

In [112]:
df_desde_numpy = pd.DataFrame(array_np1, columns=['Columna1', 'Columna2'])
df_desde_numpy

Columna1  Columna2
0         1         2
1         3         4
2         5         6