## Analisis de Datos Metereologicos


In [1]:
import pandas as pd
import numpy as np

1.- Dataframe a partir de un archivo


In [ ]:
ruta = "/home/anderson-josue/Documents/Data Science/Day 8 /datos_meteorologicos.csv"
df = pd.read_csv(ruta)

2.- Realizar observaciones iniciales


In [3]:
df

Fecha  Temperatura  Precipitación    Humedad
0     01/01/2010    17.440675      10.957482  52.384637
1     02/01/2010    25.759468       5.315628  30.633530
2     03/01/2010    20.138169      15.317706  41.496715
3     04/01/2010    17.244159      13.151008  90.684704
4     05/01/2010    11.182740      16.413667  22.116422
...          ...          ...            ...        ...
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

In [4]:
df.describe()

Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB


3.- Convertir las columnas de dataframe en numpy array


In [ ]:
array = np.genfromtxt(ruta, delimiter=",", skip_header=1)

In [8]:
array

array([[        nan, 17.4406752 , 10.957482  , 52.38463749],
       [        nan, 25.75946832,  5.31562765, 30.63352983],
       [        nan, 20.1381688 , 15.31770609, 41.49671458],
       ...,
       [        nan, 29.87359717,  4.61501177, 18.36284738],
       [        nan,         nan,         nan,         nan],
       [        nan, 37.30804318,  7.33051023, 50.64621058]])

4.- Identificarlos datos faltantes en los arrays, y reemplazarlos por le promedio


In [ ]:
temperatura_promedio = np.nanmean(array[:, 1])
array[:, 1] = np.where(np.isnan(array[:, 1]), temperatura_promedio, array[:, 1])
array

array([[        nan, 17.4406752 , 10.957482  , 52.38463749],
       [        nan, 25.75946832,  5.31562765, 30.63352983],
       [        nan, 20.1381688 , 15.31770609, 41.49671458],
       ...,
       [        nan, 29.87359717,  4.61501177, 18.36284738],
       [        nan, 14.88929572,         nan,         nan],
       [        nan, 37.30804318,  7.33051023, 50.64621058]])

In [ ]:
precipitacion_promedio = np.nanmean(array[:, 2])
array[:, 2] = np.where(np.isnan(array[:, 2]), precipitacion_promedio, array[:, 2])
array

array([[        nan, 17.4406752 , 10.957482  , 52.38463749],
       [        nan, 25.75946832,  5.31562765, 30.63352983],
       [        nan, 20.1381688 , 15.31770609, 41.49671458],
       ...,
       [        nan, 29.87359717,  4.61501177, 18.36284738],
       [        nan, 14.88929572,  9.9016036 ,         nan],
       [        nan, 37.30804318,  7.33051023, 50.64621058]])

In [ ]:
humedad_promedio = np.nanmean(array[:, 3])
array[:, 3] = np.where(np.isnan(array[:, 3]), humedad_promedio, array[:, 3])
array

array([[        nan, 17.4406752 , 10.957482  , 52.38463749],
       [        nan, 25.75946832,  5.31562765, 30.63352983],
       [        nan, 20.1381688 , 15.31770609, 41.49671458],
       ...,
       [        nan, 29.87359717,  4.61501177, 18.36284738],
       [        nan, 14.88929572,  9.9016036 , 54.3590608 ],
       [        nan, 37.30804318,  7.33051023, 50.64621058]])

5.- Analisis estadisticos


5.1 Temperatura promedio


In [ ]:
temperatura_promedio_no_nan = np.nanmean(array[:, 1])
promedio_temperatura = np.round(temperatura_promedio_no_nan, 1)
f"La temperatura promedio es: {promedio_temperatura}"

'La temperatura promedio es: 14.9'

5.2 Total de precipitaciones


In [ ]:
total_precipitacion = np.round(np.nansum(array[:, 2]), 2)
f"La cantidad total de precipitaciones es: {total_precipitacion}"


'La cantidad total de precipitaciones es: 50597.19'

5.3 Maxima humedad registrada


In [39]:
maxima_humedad = np.round(np.max(array[:, 1]))
f'La humedad maxima es" {maxima_humedad}'

'La humedad maxima es" 40.0'

5.4 Fecha mas calurosa


In [ ]:
fecha_mas_calurosa = array[np.argmax(array[:, 1]), 1]
registro_mas_caluroso = np.where(array[:, 1] == fecha_mas_calurosa)[0][0]
fecha_calurosa = df.iloc[registro_mas_caluroso]["Fecha"]
fecha_calurosa

'12/07/2017'

5.5 Fecha mas fria


In [ ]:
fecha_mas_fria = array[np.argmin(array[:, 1]), 1]
registro_mas_frip = np.where(array[:, 1] == fecha_mas_fria)[0][0]
fecha_fria = df.iloc[registro_mas_frip]["Fecha"]
fecha_fria

'23/07/2020'

6.- Guardar en csv


In [38]:
array

array([[        nan, 17.4406752 , 10.957482  , 52.38463749],
       [        nan, 25.75946832,  5.31562765, 30.63352983],
       [        nan, 20.1381688 , 15.31770609, 41.49671458],
       ...,
       [        nan, 29.87359717,  4.61501177, 18.36284738],
       [        nan, 14.88929572,  9.9016036 , 54.3590608 ],
       [        nan, 37.30804318,  7.33051023, 50.64621058]])

In [ ]:
resultados = pd.DataFrame(
    {
        "Metrica": [
            "Temperatura Promedio",
            "Precipitacion Total",
            "Humedad Maxima",
            "Dia mas caluroso",
            "Dia mas frio",
        ],
        "Valor": [
            promedio_temperatura,
            total_precipitacion,
            maxima_humedad,
            fecha_calurosa,
            fecha_fria,
        ],
    }
)

resultados.to_csv("resultados_meterologicos.csv", index=False)